### ISSUE TITLE
Bump to 1.0

### ISSUE THREAD

**Issue by alextes** [LinusU/buffer-alloc#2]
Why is this not marked stable yet?
Anything I can do to help? ^^

Now you get scary labels like seen [here](https://npms.io/search?q=buffer+alloc+ponyfill).

**Comment by LinusU** [comment]
I will bump tonight (Swedish time, in about 8 hours), feel free to remind me if I miss it :)

**Comment by alextes** [comment]
I'm fairly positive you missed it 😉

**Comment by LinusU** [comment]
Sorry about that, fixed it now 👌 

Thanks for the reminder 🎉
