### ISSUE TITLE
Missing full license text

### ISSUE THREAD

**Issue by alexdima** [LinusU/buffer-alloc#4]
The MIT license explicitly requires to attach the full license text to the code or any distribution. Without this the license isn't fulfilled by the project itself and thus invalid. Also, the license requires a Copyright statement with your name and a year (see https://opensource.org/licenses/MIT).

**Comment by alexdima** [comment]
Thank you for the prompt resolution @LinusU :heart:

I could now [remove our manual overrides](https://github.com/Microsoft/vscode/commit/bf8c26d202e12793994aa75f71335b0f01bdbad9) for our OSS tool and the next version of VS Code will credit you using your license text verbatim.

**Comment by LinusU** [comment]
No problem at all!

Really nice to know that a little part of my code is in VS Code ❤️ it's my favorite editor and daily driver!
